import json
import argparse
import os
import shutil
from pathlib import Path

def generate_slides(json_path, output_path):
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    slides_data = data.get("slides", [])
    if not slides_data:
        print("No slides found in data.")
        return

    json_file = Path(json_path)
    lecture_id = json_file.stem.replace("lec_", "")
    
    assets_base = Path("data/assets")
    assets_source = None
    
    if assets_base.exists():
        for dir_path in assets_base.iterdir():
            if dir_path.is_dir() and dir_path.name.startswith(lecture_id):
                assets_source = dir_path / "images"
                break
    
    assets_dest = Path("slidev/public/assets")
    
    if assets_dest.exists():
        for old_file in assets_dest.glob("*"):
            if old_file.is_file():
                old_file.unlink()
    
    assets_dest.mkdir(parents=True, exist_ok=True)
    
    image_ids = set()
    for slide in slides_data:
        image_data = slide.get("image")
        if isinstance(image_data, dict):
            image_id = image_data.get("image_id")
            if image_id:
                image_ids.add(image_id)
    
    if assets_source and assets_source.exists():
        for image_id in image_ids:
            for ext in ['.png', '.jpg', '.jpeg']:
                src_file = assets_source / f"{image_id}{ext}"
                if src_file.exists():
                    shutil.copy2(src_file, assets_dest / src_file.name)
                    break

    markdown_output = [
        "---",
        "theme: seriph",
        "background: https://cover.sli.dev",
        "class: text-center",
        "highlighter: shiki",
        "lineNumbers: false",
        "info: |",
        "  ## Lecture Slides",
        "  Generated by Slidev Generator",
        "drawings:",
        "  persist: false",
        "transition: slide-left",
        "title: Lecture Slides",
        "---",
        ""
    ]

    for i, slide in enumerate(slides_data):
        slide_type = slide.get("slide_type", "content")
        title = slide.get("title", "").replace('"', '\\"')
        content = slide.get("content", [])
        image_data = slide.get("image")
        
        image = None
        if isinstance(image_data, dict):
            image_id = image_data.get("image_id")
            if image_id:
                image = f"/assets/{image_id}.png"
            elif image_data.get("url"):
                image = image_data.get("url")
        elif isinstance(image_data, str):
            image = image_data
            
        has_image = bool(image)
        if isinstance(content, str):
            content = [content]
        
        content_len = len(content)
        
        layout = "default"
        
        if slide_type == "intro" or i == 0:
            layout = "cover"
        elif has_image:
            layout = "image-right"
        elif content_len == 1 and len(content[0]) < 150:
             layout = "center"
        else:
            layout = "default"
             
        md_chunk = f"---\nlayout: {layout}\n"
        
        if image and layout == "image-right":
            md_chunk += f'image: "{image}"\n'
            
            
        md_chunk += "---\n\n"
        
        if layout == "cover":
            md_chunk += f"# {title}\n\n"
            for item in content:
                md_chunk += f"{item}\n\n"
                
        elif layout == "image-right":
            md_chunk += f"# {title}\n\n"
            for item in content:
                 md_chunk += f"- {item}\n"
            
        elif layout == "center":
            md_chunk += f"# {title}\n\n"
            for item in content:
                md_chunk += f"{item}\n"
                
        else:
            md_chunk += f"# {title}\n\n"
            for item in content:
                md_chunk += f"- {item}\n"
                
        markdown_output.append(md_chunk)

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(markdown_output))

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("input_json")
    parser.add_argument("output_md")
    args = parser.parse_args()
    generate_slides(args.input_json, args.output_md)
